name: recipe_tadka
description: RECIPE TADKA - Food Recipe app with VIP/Admin

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0

  # Google Sign-In
  google_sign_in: ^6.2.1

  # HTTP for REST API
  http: ^1.2.0

  # State management
  provider: ^6.1.0

  # Fonts / modern UI
  google_fonts: ^6.2.0
  hive: ^2.2.3
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Add this line

flutter:
  uses-material-design: true